version: '3'

volumes:
  static_volume: {}
  media_volume: {}
  data_volume: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    volumes:
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/worldmath/media
    command: /start
    depends_on:
      - postgres

  nginx:
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    volumes:
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/worldmath/media
    ports:
      - 83:80
    depends_on:
      - django

  postgres:
    image: postgres:16.1
    volumes:
      - data_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env.postgres
    ports:
      - 5432:5432